### ISSUE TITLE
Regex for [] and {}?

### ISSUE THREAD

**Issue by vemv** [tarsius/paren-face#6]
Hi,

great package, working as advertised!

I'm occasionally bad at regex. How should one fill `paren-face-regexp` to match []/{} too?

Since it can be a FAQ, seems worth placing it as a comment in https://github.com/tarsius/paren-face/blob/0a7cbd65bb578cc52a9dc495a4fcaf23a57507bf/paren-face.el#L84 .

Cheers - Victor

**Comment by tarsius** [comment]
I've added such a comment. Here's an extended description:

```
"[][(){}]"
 |------|---  any of the characters within
  |---------  an empty set would not make sense
              so this is just one of the "characters within"
   |--------  we are already inside [...], which cannot be nested
              so this is just one of the "characters within"
    ||||----  as usual
```

**Comment by vemv** [comment]
Works flawlessly - thanks!
